version: '3'

services:

  web:
    container_name: 'aspnetcore-from-compose'
    image: 'aspnetcore-from-compose'
    build:
      context: .
      dockerfile: Dockerfile.EntrypointScript
    volumes:
      - .:/app
    entrypoint: ["sh", "./go.sh"] 
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
    networks:
      - app-network

  postgres:
    container_name: 'postgres-from-compose'
    image: postgres
    environment:
      POSTGRES_PASSWORD: pgPassword
    networks:
      - app-network
    volumes:
      - 'postgres:/var/lib/postgresql/data'

networks:
  app-network:
    driver: bridge

volumes:
 postgres: {}